Adding OIDC auth

diff --git a/.github/workflows/sonar-ci.yml b/.github/workflows/sonar-ci.yml
--- a/.github/workflows/sonar-ci.yml
+++ b/.github/workflows/sonar-ci.yml
@@ -30,17 +30,21 @@ jobs:
           cache: 'npm'
           cache-dependency-path: 'cf-graphdb-app/package-lock.json'
 
-      - name: 🧪 Test & Generate Coverage
+      - name: 🧪 Run Vitest with temp .env
         shell: bash
         run: |
-          set -e
-          trap 'rm -f .dev.vars.stage' EXIT
+          set -e          # fail on first error in main command block
+          trap 'rm -f .dev.vars.stage' EXIT  # always delete .dev.vars.stage on exit
           echo "JWT_SECRET=${{ secrets.ENV_JWT_SECRET }}" > .dev.vars.stage
           echo "TOGETHER_API_KEY=${{ secrets.TOGETHER_API_KEY }}" >> .dev.vars.stage
           echo "QDRANT_API_KEY=${{ secrets.QDRANT_API_KEY }}" >> .dev.vars.stage
           echo "QDRANT_EDGE_COLLECTION=${{ secrets.QDRANT_EDGE_COLLECTION }}" >> .dev.vars.stage
           echo "QDRANT_URL=${{ secrets.QDRANT_URL }}" >> .dev.vars.stage
-          npm install
+          echo "OIDC_CLIENT_SECRET=${{ secrets.OIDC_CLIENT_SECRET }}" >> .dev.vars.stage
+          echo "OIDC_CLIENT_ID=${{ secrets.OIDC_CLIENT_ID }}" >> .dev.vars.stage
+          echo "OIDC_DISCOVERY_URL=${{ secrets.OIDC_DISCOVERY_URL }}" >> .dev.vars.stage
+          echo "KEYCLOAK_TEST_PASS=${{ secrets.KEYCLOAK_TEST_PASS }}" >> .dev.vars.stage
+          echo "KEYCLOAK_TEST_USER=${{ secrets.KEYCLOAK_TEST_USER }}" >> .dev.vars.stage
           npm run ci:stage
         env:
           NODE_ENV: stage
